version: '3.1' # docker compose version

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATAVASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/Mysql-snippets/:/sqlfiles
